config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'

  get 'categories/index'

  resources :products, :categories
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :opinions
  #get "/opinions/:id", to: "opinions#show"
  
  get 'users/index'
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show"
  
  root "welcome#index"
end


#devise_for :users, controllers: { sessions: 'user/sessions' }
#devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

#get '/user/sign_up', to: 'user/registrations#new'


# get "log_out" => "session#destroy", :as => "log_out"
# get "log_in" => "session#new", :as => "log_in"
# get "sign_up" => "users#new", :as => "sign_up"
# root :to => "users#new"
# resources :users

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :user

  has_attached_file :proof,
                    url: "/system/:hash.:extension",
                    hash_secret: "abc123",
                    styles: { medium: ["301x301#", :jpg], thumb: ["100x100#", :jpg] }
  validates_attachment_content_type :proof, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authenticate_user!, :set_opinion, only: [:show, :edit, :update, :destroy]
  before_action :belongs_to_current_user, only: [:destroy, :edit]
  helper_method :belongs_to_current_user
  
  # GET /opinions
  # GET /opinions.json
  def index
    @opinions = Opinion.all
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show
  
  end

  # GET /opinions/new
  def new
    @opinion = Opinion.new
  end

  # GET /opinions/1/edit
  def edit
    if !belongs_to_current_user
      respond_to do |format|
        format.html { redirect_to @opinion, notice: "You're not authorised to do this" }
      end
    end
  end

  # POST /opinions
  # POST /opinions.json
  def create
    if user_signed_in?
      # @opinion = Opinion.new({preview:opinion_params[:preview], explanation:opinion_params[:explanation], proof:opinion_params[:proof], user_id: current_user.id})
      @opinion = Opinion.new(opinion_params)
      @opinion.user = current_user
      respond_to do |format|
        if @opinion.save
          format.html { redirect_to @opinion, notice: 'Opinion was successfully created for this user!'}
          format.json { render :show, status: :created, location: @opinion }
        else
          format.html { render :new }
          format.json { render json: @opinion.errors, status: :unprocessable_entity }
        end
      end
    
    end
  end

  # PATCH/PUT /opinions/1
  # PATCH/PUT /opinions/1.json
  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    if belongs_to_current_user or current_user.supplier?
      @opinion.destroy

      respond_to do |format|
        format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
        format.json { head :no_content }
      end
      
    end
  end


  def belongs_to_current_user
    current_user.id == @opinion.user_id
  end
  

  private

  
    # Use callbacks to share common setup or constraints between actions.
    def set_opinion
      @opinion = Opinion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opinion_params
      params.require(:opinion).permit(:preview, :explanation, :proof, :user_id)
    end
  
    
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.erb
<%= form_with(model: opinion, local: true, class: 'form-horizontal' ) do |form|%>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
      <% opinion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :preview, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :preview, id: :opinion_preview, class: "form-control", placeholder: "Enter a preview"  %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :explanation, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :explanation, id: :opinion_explanation, class: "form-control", placeholder: "Enter a explanation"  %>
    </div>
  </div>


  <div class="form-group">
    <%= form.label :proof, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.file_field :proof, id: :opinion_explanation, class: "form-control"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/opinions/_list.html.erb
<div class="row text-center">

  <% opinions.each do |opinion| %>

    <div class="col-lg-3 col-md-6 mb-4">
      <div class="card">

        <%= link_to image_tag(opinion.proof.url(:medium), class: 'card-img-top img-rounded'), opinion.proof.url %>

        <div class="card-body">
          <h4 class="card-title"><%= link_to opinion.preview, opinion, class: 'btn-link text-info' %></h4>
        </div>

        <div class="card-footer">
          <p class="card-text">
            <%= link_to opinion.explanation, opinion, class: 'btn-link text-muted' %>
          </p>

          <% if current_user.id == opinion.user_id or current_user.supplier? %>
          <div>
            <%= link_to 'Edit', edit_opinion_path(opinion), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<h1>Opinions</h1>

<!--%=# render :partial => 'list', :locals => {:opinions => @opinions } %-->

<%= render 'list', opinions: @opinions %>

<br>

<% if current_user.supplier? %>
<%= link_to 'New Opinion', new_opinion_path %>
<% end %>

app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p>
  <strong>Preview:</strong>
  <%= @opinion.preview %>
</p>

<p>
  <strong>Explanation:</strong>
  <%= @opinion.explanation %>
</p>

<p>
  <strong>User:</strong>
  <%= @opinion.user.username %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>