config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'

  get 'categories/index'

  resources :products, :categories
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :opinions
  #get "/opinions/:id", to: "opinions#show"
  
  get 'users/index'
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show"
  
  root "welcome#index"
end


#devise_for :users, controllers: { sessions: 'user/sessions' }
#devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

#get '/user/sign_up', to: 'user/registrations#new'


# get "log_out" => "session#destroy", :as => "log_out"
# get "log_in" => "session#new", :as => "log_in"
# get "sign_up" => "users#new", :as => "sign_up"
# root :to => "users#new"
# resources :users

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :user

  has_attached_file :thumbnail,
                    url: "/system/:hash.:extension",
                    hash_secret: "abc123",
                    styles: { medium: ["301x301#", :jpg], high: ["700x700#", :jpg]}
  validates_attachment_content_type :thumbnail, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :belongs_to_current_user, only: [:destroy, :edit]
  helper_method :belongs_to_current_user
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @supplier = User.find(@product.user_id)
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    if current_user.supplier?
      @product = Product.new(product_params)
      @product.user = current_user
      respond_to do |format|
        if @product.save
          format.html { redirect_to @product, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def belongs_to_current_user
    current_user.id == @product.user_id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :title, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :title, id: :product_title, class: "form-control", placeholder: "Enter a title"  %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_area :description, id: :product_description, class: "form-control", placeholder: "Enter a description"  %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :price, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.number_field :price, id: :product_price, class: "form-control", placeholder: "Enter a price"  %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label 'Categories:', class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <% @categories.each do |category| %>
        <%= check_box_tag "product[category_ids][]", category.id, product.categories.include?(category) %>
        <%= category.name %><br />
      <% end %>
    </div>
  </div>


  <div class="form-group">
    <%= form.label :thumbnail, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.file_field :thumbnail, id: :opinion_explanation, class: "form-control"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_list.html.erb
<div class="row text-center">

  <% products.each do |product| %>

    <div class="col-lg-3 col-md-6 mb-4">
      <div class="card">

        <br/>

        <%= link_to image_tag(product.thumbnail.url(:medium), class: 'card-img-top img-rounded'), product %>

        <div class="card-body">
          <h4 class="card-title">
            <%= link_to  product.title, product, class: 'btn-link text-info'%>
          </h4>
        </div>

        <div class="card-footer">
          <p class="card-text">
            <%= link_to "Price: " + product.price.to_s, product, class: 'btn-link text-muted' %>
          </p>
          <% if current_user.id == product.user_id or current_user.supplier? %>
            <div>
              <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary' %>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
            </div>
          <% end %>
        </div>

      </div>
    </div>

  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>


<%= render 'list', products: @products %>

<br>

<% if current_user.supplier? %>
<%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= link_to @supplier.username, "/users/" + @supplier.id.to_s  %>
</p>

<p>
  <strong>Categories:</strong>

  <% @product.categories.each do |category| %>
    <%= link_to category.name, "/categories/" + category.id.to_s  %>
  <% end %>
</p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>